# A template must be specified
template: self
admin_email: info@codecomment.io
site_title: Starter Template
default_language: en
languages:
    - en
    - fr
blog: codecomment
blog_base: /blog
# You can have multiple menus with different names.
# The key for each menu item is the route name, defined in pages.yml
menu:
    main:
        home:
            text: Home
            attributes:
                class: menu-item
        about:
            text: About
            attributes:
                class: menu-item
        blog:
            text: Blog
            attributes:
                class: menu-item
        "#contact":
            text: Contact
            attributes:
                class: menu-item
        "http://ubiweb.com":
            text: Ubiweb
            attributes:
                class: menu-item
